Feature/la 35703 ds survey category labeling integration for doccano
taboola/doccano pull request #1
Opened 2021-02-23 08:44 UTC by chihyikuan

2021-02-23 09:25 UTC, amjltc295 requested changes

2021-02-23 09:25 UTC, amjltc295 commented on Dockerfile
> +
Please remove useless empty lines

2021-02-23 09:25 UTC, amjltc295 commented on frontend/components/containers/annotation/TextClassification.vue
> +        :labels="itemsl"
Could you rename it as itemsSecondLevel?

2021-02-23 09:25 UTC, amjltc295 commented on frontend/components/containers/annotation/TextClassification.vue
> +        console.log('level1', state)
Please remove debugging logs

2021-02-23 09:43 UTC, chihyikuan commented
Done modify reviewed issue. @amjltc295

2021-02-24 02:20 UTC, amjltc295 approved these changes

2021-02-24 02:21 UTC, amjltc295 commented
We have to fix https://github.com/doccano/doccano/pull/1197

2021-02-24 02:21 UTC, merged